spring:
  devtools:
    restart:
      enabled: true
  security:
    user:
      name: admin
      password: admin
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pokeapi
    username: postgres
    password: 12345
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    
logging:
  level:
    com:
      mx:
        pokeapi:
          feign:
            client: DEBUG
            

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        --loggerLevel: basic
        loggerLevel: full
        
        
pokeapi:
  feign:
    url: https://pokeapi.co/api/v2/pokemon





