spring:
  devtools:
    restart:
      enabled: true
  security:
    user:
      name: admin
      password: admin
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pokeapi
    username: postgres
    password: 12345
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
      okhttp:
        enabled: true
    
logging:
  level:
    com:
      mx:
        pokeapi:
          feign:
            client: debug
            
                        
#feign:
#  client:
##    default-to-properties: false
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: basic
#  okhttp:
#    enabled: true
        
        
pokeapi:
  feign:
    url: https://pokeapi.co/api/v2





